### ISSUE TITLE
"Unfortunately, Unit5-App has stopped."

### ISSUE THREAD

**Issue by bepzi** [Afulton11/Unit5-App#1]
Stacktrace:

FATAL EXCEPTION: main
                                                              Process: com.unit5app, PID: 29630
                                                              java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                  at java.util.ArrayList.remove(ArrayList.java:403)
                                                                  at com.unit5app.com.unit5app.parsers.RSSReader.getCalendarEvents(RSSReader.java:190)
                                                                  at com.unit5app.UpcomingEventsActivity$ReadCalendarTask.onPostExecute(UpcomingEventsActivity.java:71)
                                                                  at com.unit5app.UpcomingEventsActivity$ReadCalendarTask.onPostExecute(UpcomingEventsActivity.java:59)
                                                                  at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                  at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                  at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)

Due to ReadCalendarTask not being finished?

**Comment by Afulton11** [comment]
yes, i fixed it by returning a blank calendar list if the reader is not yet done parsing when the textView requests the calendar information. The textView should update within the next 10 seconds when the calendar reader is done parsing. As of right now the endOfHourHandler only works when connected to the internet, however this can easily be fixed to work offline in the future. The only thing it needs the internet for is to check if there is no school today or if today is a late start.
